import "@testing-library/jest-dom";

Object.defineProperty(window, "matchMedia", {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => {},
  }),
});

const mockContext: CanvasRenderingContext2D = {
  canvas: document.createElement("canvas"),
  save: () => {},
  restore: () => {},
  scale: () => {},
  rotate: () => {},
  translate: () => {},
  transform: () => {},
  setTransform: () => {},
  clearRect: () => {},
  fillRect: () => {},
  strokeRect: () => {},
  beginPath: () => {},
  closePath: () => {},
  moveTo: () => {},
  lineTo: () => {},
  bezierCurveTo: () => {},
  quadraticCurveTo: () => {},
  arc: () => {},
  arcTo: () => {},
  ellipse: () => {},
  rect: () => {},
  fill: () => {},
  stroke: () => {},
  clip: () => {},
  createLinearGradient: () => ({ addColorStop: () => {} }) as unknown as CanvasGradient,
  createRadialGradient: () => ({ addColorStop: () => {} }) as unknown as CanvasGradient,
  createPattern: () => null,
  fillText: () => {},
  strokeText: () => {},
  measureText: () => ({ width: 0, actualBoundingBoxAscent: 0, actualBoundingBoxDescent: 0 }),
  drawImage: () => {},
  createImageData: () => ({ data: new Uint8ClampedArray(0), width: 0, height: 0 }),
  getImageData: () => ({ data: new Uint8ClampedArray(0), width: 0, height: 0 }),
  putImageData: () => {},
  globalAlpha: 1,
  globalCompositeOperation: "source-over",
  imageSmoothingEnabled: true,
  imageSmoothingQuality: "low",
  strokeStyle: "#000",
  fillStyle: "#000",
  shadowBlur: 0,
  shadowColor: "#000",
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  lineWidth: 1,
  lineCap: "butt",
  lineJoin: "miter",
  miterLimit: 10,
  lineDashOffset: 0,
  font: "10px sans-serif",
  textAlign: "start",
  textBaseline: "alphabetic",
  direction: "ltr",
  filter: "none",
  setLineDash: () => {},
  getLineDash: () => [],
  setScrollTransform: () => {},
  setFontKerning: () => {},
  setLetterSpacing: () => {},
  setTextRendering: () => {},
  setWordSpacing: () => {},
} as unknown as CanvasRenderingContext2D;

HTMLCanvasElement.prototype.getContext = (() => mockContext) as unknown as typeof HTMLCanvasElement.prototype.getContext;
